// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49yvdeni7bDIxn0WcnxdRFasrWXNQrUY',
    appId: '1:577597517701:web:29eee70fb10589954b9eec',
    messagingSenderId: '577597517701',
    projectId: 'socialmedia-7711f',
    authDomain: 'socialmedia-7711f.firebaseapp.com',
    storageBucket: 'socialmedia-7711f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu2mIQa_qcmEXakJDo9u7YSsnOYrZexJ4',
    appId: '1:577597517701:android:40fc0a680eb860904b9eec',
    messagingSenderId: '577597517701',
    projectId: 'socialmedia-7711f',
    storageBucket: 'socialmedia-7711f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfY6_j5KXD8wTlfLOhPfOwcqWNI3e_L0',
    appId: '1:577597517701:ios:84f82caf106b48844b9eec',
    messagingSenderId: '577597517701',
    projectId: 'socialmedia-7711f',
    storageBucket: 'socialmedia-7711f.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfY6_j5KXD8wTlfLOhPfOwcqWNI3e_L0',
    appId: '1:577597517701:ios:84f82caf106b48844b9eec',
    messagingSenderId: '577597517701',
    projectId: 'socialmedia-7711f',
    storageBucket: 'socialmedia-7711f.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB49yvdeni7bDIxn0WcnxdRFasrWXNQrUY',
    appId: '1:577597517701:web:bafea10fbfab28204b9eec',
    messagingSenderId: '577597517701',
    projectId: 'socialmedia-7711f',
    authDomain: 'socialmedia-7711f.firebaseapp.com',
    storageBucket: 'socialmedia-7711f.appspot.com',
  );
}
